### ISSUE TITLE
How do we login

### ISSUE THREAD

**Issue by denohpakni** [smbugua/Payroll-System-2018#1]
You didnt specifiy how a user or admin can login. I couldnt find a root password and username. I changed the entries on connect.php but still couldnt go through

**Comment by smbugua** [comment]
please contact me directly on my email .
smbugua11@gmail.com

**Comment by smbugua** [comment]
please clone the repo the upload this mysql db on your localhost
then edit auth file for db credentials:
username for login : admin@hr.com
password : admin
then download the sql from the latest commit

**Comment by denohpakni** [comment]
Error is:
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\Program Files\Ampps\www\Payroll-System-2018\main\connect.php:7 Stack trace: #0 C:\Program Files\Ampps\www\Payroll-System-2018\main\signin.php(2): include() #1 {main} thrown in C:\Program Files\Ampps\www\Payroll-System-2018\main\connect.php on line 7

My connect.php
<?php // rnfunctions.php
error_reporting(E_ALL ^ E_DEPRECATED);
$dbhost = 'localhost'; // Unlikely to require changing
$dbname = 'smbuguapayroll'; // Modify these...
$dbuser = 'root'; // ...variables according
$dbpass = 'mysql'; // ...to your installation
mysql_connect($dbhost, $dbuser, $dbpass) or die(mysql_error());
mysql_select_db($dbname) or die(mysql_error());

NB: I have created the "smbuguapayroll" database in my localhost, and its empty with no tables

**Comment by denohpakni** [comment]
Hi Mbugua,This didn’t work for me.Error is: Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\Program Files\Ampps\www\Payroll-System-2018\main\connect.php:7 Stack trace: #0 C:\Program Files\Ampps\www\Payroll-System-2018\main\signin.php(2): include() #1 {main} thrown in C:\Program Files\Ampps\www\Payroll-System-2018\main\connect.php on line 7 My connect.php<?php // rnfunctions.phperror_reporting(E_ALL ^ E_DEPRECATED);$dbhost = 'localhost'; // Unlikely to require changing$dbname = 'smbuguapayroll'; // Modify these...$dbuser = 'root'; // ...variables according$dbpass = 'mysql'; // ...to your installationmysql_connect($dbhost, $dbuser, $dbpass) or die(mysql_error());mysql_select_db($dbname) or die(mysql_error()); NB: I have created the "smbuguapayroll" database in my localhost, and its empty with no tables Sent from Mail for Windows 10 From: simon mbuguaSent: Friday, January 24, 2020 4:38 PMTo: smbugua/Payroll-System-2018Cc: Denoh; AuthorSubject: Re: [smbugua/Payroll-System-2018] How do we login (#1) please clone the repo the upload this mysql db on your localhostthen edit auth file for db credentials:username for login : admin@hr.compassword : adminthen download the sql from the latest commit—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by smbugua** [comment]
Please use php 5.5

Regards,
Mbugua Simon,
Software Developer | Systems Architect | DevOps Engineer & Digital
Consultancy
Tel: +254-728-944815
online:https://www.mbugua.co.ke/

**Comment by smbugua** [comment]
did you succeed?
